Stub for `Morphism.agda`
agda/agda-categories pull request #317
Opened 2021-10-30 19:42 UTC by tetrapharmakon

Monad morphisms, in two flavours.

2021-11-04 19:42 UTC, JacquesCarette commented
As this is clearly still a work in progress, I've marked it as 'draft'.

2021-11-07 20:17 UTC, tetrapharmakon commented
This module is ready for review, but suggestions on extensions are welcome by me or @iwilare 

Cheers!

2021-11-09 23:09 UTC, JacquesCarette requested changes
Mostly minor things. That and I've taken to use a lot of `using` clauses. It acts as nice documentation of what's actually needed.

2021-11-09 23:09 UTC, JacquesCarette commented on src/Categories/Monad/Morphism.agda
> +  module M = Monad M
I would tend to make all of these `private`, otherwise they all appear on the interface for `Monad⇒`

2021-11-09 23:09 UTC, JacquesCarette commented on src/Categories/Monad/Morphism.agda
> +  open D
I would tend to put a `using` clause, to narrow down the name pollution.

2021-11-09 23:09 UTC, JacquesCarette commented on src/Categories/Monad/Morphism.agda
> +  module M = Monad M
The modules `N` and `C` do not appear to be used below?

2021-11-09 23:09 UTC, JacquesCarette commented on src/Categories/Monad/Morphism.agda
> +    m : NaturalTransformation (Monad⇒.X Γ) (Monad⇒.X Δ)
```NaturalTransformation Γ.X Δ.x``` ?

2021-11-20 13:57 UTC, JacquesCarette approved these changes

2021-11-20 15:09 UTC, merged