F-Coalgebras forma category
agda/agda-categories pull request #354
Opened 2022-10-05 06:30 UTC by Taneb

More or less copied from the F-Algebras category. I wanted this while I was messing around with recursion schemes a while back.

2022-10-11 10:44 UTC, JacquesCarette requested changes
Thanks!  Could you also put some 'using' clauses in your local `open`s? They actually make the resulting saved interface smaller, and are useful documentation.

2022-10-11 10:44 UTC, JacquesCarette commented on src/Categories/Functor/Coalgebra.agda
> +  module X = F-Coalgebra X
Can you make these 2 modules 1) private, and 2) qualified with `using` clauses so that they are smaller?

2023-05-11 07:20 UTC, t-wissmann commented
Thanks for implementing this -- it also would be useful for me, too!

By the way, there is a space missing in the PR title ('forma' -> 'form a').

2023-05-22 15:54 UTC, JacquesCarette approved these changes

2023-05-22 15:54 UTC, JacquesCarette commented
Sorry to be so slow to review this. But now there's a conflict... can you resolve, and then I can merge?

2023-05-22 18:54 UTC, Taneb commented
This was added in #362

2023-05-22 18:54 UTC, closed without merging