Properties of distributive categories
agda/agda-categories pull request #410
Opened 2024-01-25 15:35 UTC by Reijix

I've added some properties of the distribution isos in `Categories.Category.Distributive` that I am using in my personal project.

Im very open for naming suggestions for these properties, the current names might not be that good.

I also thought about putting them in `Categories.Category.Distributive.Properties` but it seems to me that as soon as you are working with distributive categories you will need (some of) these helpers.

2024-01-26 20:06 UTC, JacquesCarette requested changes
While I agree that these are often needed as soon as you deal with Distributive categories, for scalability we've found that putting a lot of properties in the defining record tends to really bloat things up further down the line. So even though it is less convenient, putting them in `Categories.Category.Distributive.Properties` would scale better.

Another possibility is to define `Distributive` in ...`Distributive.Core` (and open it public in this file) and then leave all of these definitions here.  

Either of those would be fine with me.

2024-01-26 20:06 UTC, JacquesCarette commented
Should have said: really nice work. I do want to pull this in!

2024-01-27 15:07 UTC, Reijix commented
Good point, I moved the properties to `Categories.Category.Distributive.Properties`.

2024-01-28 14:11 UTC, JacquesCarette approved these changes

2024-01-28 14:11 UTC, merged