Add constructions for Monads and Comonads
agda/agda-categories pull request #412
Opened 2024-02-27 15:28 UTC by 4e554c4c

This commit adds a few constructions for monads and comonads. In particular, it adds the identity monad and comonad for a category. It also adds the identity and composite morphism between monads on the same category.

2024-02-27 16:23 UTC, JacquesCarette commented
FYI: might be a few days before I can properly review this. Very welcome additions, I'm just facing a number of deadlines at the moment.

2024-03-03 17:03 UTC, JacquesCarette requested changes
Only some cosmetic changes, nice.

2024-03-03 17:03 UTC, JacquesCarette commented on src/Categories/Comonad/Morphism.agda
> +    ≈⟨ C.sym-assoc ⟩
Various uses of push / pull / assoc2 etc can likely shorten this proof too.

2024-03-03 17:03 UTC, JacquesCarette commented on src/Categories/Monad.agda
> +  idM : Monad C
Just `id`

2024-03-03 17:03 UTC, JacquesCarette commented on src/Categories/Monad/Morphism.agda
> +  Monad⇒-id-id .mult-comp {U} = begin
Here and below: all the same comments as for Comonad apply.

2024-03-04 09:58 UTC, 4e554c4c commented on src/Categories/Comonad/Morphism.agda
> +open import Categories.Comonad
Here I believe I am using everything from a module (`Comonad` and `id`)

2024-03-04 11:40 UTC, 4e554c4c commented
oops sorry for requesting review @Taneb  that was on accident

2024-03-08 15:37 UTC, JacquesCarette requested changes
Just one minor cosmetic thing left to fix (in a number of places). The rest is great - the proof-golfing really improved things.

2024-03-08 15:37 UTC, JacquesCarette commented on src/Categories/Comonad/Morphism.agda
> +    T.δ.η U ∘ id
If you don't want to do
```
lhs     reason
```
layout, please do at least 2-space indenting of the reasons.

2024-03-12 21:06 UTC, JacquesCarette submitted a review, later dismissed
Perfect!

2024-03-12 23:31 UTC, JacquesCarette commented
CI fails with
```
 Checking Categories.Monad.Strong (/home/runner/work/agda-categories/agda-categories/src/Categories/Monad/Strong.agda).
/home/runner/work/agda-categories/agda-categories/src/Categories/Monad/Strong.agda:47,43-45
Ambiguous name id. It could refer to any one of
  Categories.Monad.id bound at
    /home/runner/work/agda-categories/agda-categories/src/Categories/Monad.agda:35,3-5
  Categories.Monad.Strong.id bound at
    /home/runner/work/agda-categories/agda-categories/src/Categories/Category/Core.agda:23,5-7
id is in scope as
  * a defined name Categories.Monad._.id brought into scope by
    - the opening of Categories.Monad at /home/runner/work/agda-categories/agda-categories/src/Categories/Monad/Strong.agda:19,13-29
    - its definition at /home/runner/work/agda-categories/agda-categories/src/Categories/Monad.agda:35,3-5
  * a record field Categories.Monad.Strong._.id brought into scope by
    - the application of Category at /home/runner/work/agda-categories/agda-categories/src/Categories/Monad/Strong.agda:28,8-16
    - its definition at /home/runner/work/agda-categories/agda-categories/src/Categories/Category/Core.agda:23,5-7
when scope checking id
```

2024-03-13 15:18 UTC, 4e554c4c commented
I ran the CI locally, it seems like everything should pass now

2024-03-13 15:20 UTC, JacquesCarette approved these changes

2024-03-13 19:26 UTC, merged